baseURL = "https://williampoynter.co.uk/"
languageCode = "en-gb"
title = "Will Poynter"
theme = "resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
disableHugoGeneratorInject = true

[params]
address = "Sheffield, UK"
email = "will@williampoynter.co.uk"
favicon = "/favicon.ico"
firstName = "Will"
lastName = "Poynter"
profileImage = "img/willpoynter.webp"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = true
showTutorials = true
showQr = false
showSkills = true
description = "The professional profile of William 'Will' Poynter. Including contact information, work experience, education and past publications."

[params.google]

[params.google.analytics]
trackerID = "UA-21852562-1"

[[params.handles]]
link = "https://www.linkedin.com/in/will-poynter-3aa34416/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/wpoynter/"
name = "GitHub"

[[params.handles]]
link = "https://www.instagram.com/poynterwilliam/"
name = "Instagram"

[[params.handles]]
link = "https://stackoverflow.com/users/17143487/will-poynter"
name = "Stack Overflow"
icon = "stack-overflow"

[[params.handles]]
link = "https://keybase.io/willtinto"
name = "Keybase"

[[params.handles]]
link  = "https://researchwiseai.com/"
name  = "ResearchWiseAI"
icon  = "heart"
solid = true

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "williampoynter-co-uk"
URL = "s3://williampoynter.co.uk?region=eu-west-2"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "max-age=86400, no-transform, public"
gzip = true
