baseURL = "https://www.williampoynter.co.uk/"
languageCode = "en-gb"
title = "William Poynter"
theme = "resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "London, UK"
email = "poynter.william@gmail.com"
favicon = "/favicon.ico"
firstName = "William"
lastName = "Poynter"
phone = "+44 787 510 7860"
profileImage = "img/williampoynter.jpeg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = true
showQr = true
showSkills = true
description = "The professional profile of William 'Will' Poynter. Including contact information, work experience, education and past publications."

[params.google]

[params.google.analytics]
trackerID = "UA-21852562-1"

[[params.handles]]
link = "https://www.linkedin.com/in/will-poynter-3aa34416/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/wpoynter/"
name = "GitHub"

[[params.handles]]
link = "https://www.instagram.com/poynterwilliam/"
name = "Instagram"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "williampoynter-co-uk"
URL = "gs://www.williampoynter.co.uk/"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "max-age=300, no-transform, public"
gzip = true
