name: CD
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'

    - name: Clean public directory
      run: rm -rf public

    - name: Build
      run: hugo --minify

    - name: Install Node modules
      run: yarn

    - name: Run ESLint
      run: yarn run eslint public/

    - name: Run HTML Validation
      run: yarn run html-validate public/
      
    - name: install-aws-cli-action
      uses: unfor19/install-aws-cli-action@v1.0.3
        
    - name: Deploy
      run: hugo deploy
